version: '3'
services:
  validator-alice:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e142354
    ports:
      - '30333:30333'
      - '6644:9944'
      - '9933:9933'
    volumes:
      - ./:/data
    command:
      - --chain=/data/dex_raw.json
      - --base-path=/data/alice_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --alice
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.1
        aliases:
          - alice

  validator-bob:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e142354
    ports:
      - '30335:30333'
      - '9966:9944'
      - '9955:9933'
    volumes:
      - ./:/data
    command:
      - --chain=/data/dex_raw.json
      - --base-path=/data/bob_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.2
        aliases:
          - bob
  
  validator-charlie:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e142354
    ports:
      - '30337:30333'
      - '9988:9944'
      - '9977:9933'
    volumes:
      - ./:/data
    command:
      - --chain=/data/dex_raw.json
      - --base-path=/data/charlie_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --charlie
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.4
        aliases:
          - charlie

  validator-dave:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e142354
    ports:
      - '30339:30333'
      - '9922:9944'
      - '9911:9933'
    volumes:
      - ./:/data
    command:
      - --chain=/data/dex_raw.json
      - --base-path=/data/dave_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --dave
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.6
        aliases:
          - dave

  dex-genesis-state:
    image: subdarkdex/subdex-collator:v0.2.0
    volumes:
      - subdex-genesis-state:/subdex
    command: >
      /usr/local/bin/subdex-parachain-collator
      export-genesis-state
      /subdex/subdex-genesis-state

  generic-genesis-state:
    image: subdarkdex/generic-collator:v0.2.0
    volumes:
      - generic-genesis-state:/generic
    command: >
      /usr/local/bin/generic-parachain-collator
      export-genesis-state
      /generic/generic-genesis-state
    
  dex-collator:
    image: subdarkdex/subdex-collator:v0.2.0
    ports:
      - '40440:30333'
      - '9944:9944'
      - '6633:9933'
    volumes:
      - ./:/subdex
    depends_on:
      - validator-alice
      - validator-bob
      - validator-charlie
      - validator-dave
    command: >
      /usr/local/bin/start_dex_collator.sh
    networks:
      dex_net:
        ipv4_address: 172.28.1.8
        aliases:
          - dex-collator

  generic-collator:
    image: subdarkdex/generic-collator:v0.2.0
    ports:
      - '40444:30333'
      - '7744:9944'
      - '7733:9933'
    volumes:
      - ./:/data
    depends_on:
      - validator-alice
      - validator-bob
      - validator-charlie
      - validator-dave
    command: >
      /usr/local/bin/start_generic_collator.sh
    networks:
      dex_net:
        ipv4_address: 172.28.1.10
        aliases:
          - generic-collator

  dex-runtime:
    image: subdarkdex/subdex-runtime:v0.2.0
    volumes:
      - subdex-chain-wasm-runtime:/runtime

  generic-runtime:
    image: subdarkdex/generic-runtime:v0.2.0
    volumes:
      - generic-chain-wasm-runtime:/runtime
    
  registrar:
    image: subdarkdex/subdex-registrar:v0.2.0
    volumes:
      - subdex-genesis-state:/subdex-genesis-state
      - generic-genesis-state:/generic-genesis-state
      - subdex-chain-wasm-runtime:/subdex-chain-wasm-runtime
      - generic-chain-wasm-runtime:/generic-chain-wasm-runtime
    depends_on:
      - validator-alice
      - validator-bob
      - dex-runtime
      - generic-runtime
      - dex-genesis-state
      - generic-genesis-state
    networks:
      dex_net:

volumes:
  subdex-genesis-state:
  subdex-chain-wasm-runtime:
  generic-genesis-state:
  generic-chain-wasm-runtime:

networks:
  dex_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  
