version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
    networks:
      - dex_net
  
networks:
  dex_net:

   
