version: '3'
services:
  apps:
    image:  jacogr/polkadot-js-apps:0.69.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.apps.rule=Host(`subdex.link`)
      - traefik.http.routers.apps.tls=true
      - traefik.http.routers.apps.tls.certresolver=letsEncrypt
      - traefik.http.routers.apps.service=apps
      - traefik.http.services.apps.loadbalancer.server.port=80
    environment:
      - WS_URL=wss://subdex.link/relay
    ports:
      - '8080:80'
    networks:
      dex_net:

  validator-alice:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e142354
    labels: 
      - traefik.enable=true
      - traefik.http.routers.validatorAlice.rule=Host(`subdex.link`) && Path(`/relay`) 
      - traefik.http.routers.validatorAlice.tls=true
      - traefik.http.routers.validatorAlice.tls.certresolver=letsEncrypt
      - traefik.http.routers.validatorAlice.service=validatorAlice
      - traefik.http.services.validatorAlice.loadbalancer.server.port=9944
    ports:
      - '30333:30333'
      - '6644:9944'
      - '9933:9933'
    volumes:
      - ./chainspec:/chainspec
      - validator_alice:/data
    command:
      - --chain=/chainspec/rococo-3.json
      - --base-path=/data/tmp/alice_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --alice
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.1
        aliases:
          - alice

  validator-bob:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e142354
    ports:
      - '30335:30333'
      - '9966:9944'
      - '9955:9933'
    volumes:
      - ./chainspec:/chainspec
      - validator_bob:/data
    command:
      - --chain=/chainspec/rococo-3.json
      - --base-path=/data/tmp/bob_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.2
        aliases:
          - bob
  
  validator-charlie:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e142354
    ports:
      - '30337:30333'
      - '9988:9944'
      - '9977:9933'
    volumes:
      - ./chainspec:/chainspec
      - validator_charlie:/data
    command:
      - --chain=/chainspec/rococo-3.json
      - --base-path=/data/tmp/charlie_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --charlie
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.4
        aliases:
          - charlie

  dex-genesis-state:
    image: subdarkdex/subdex-collator:v0.2.0
    volumes:
       - subdex-genesis-state:/subdex
    command: >
      /usr/local/bin/parachain-collator
      export-genesis-state --parachain-id=200 

      /subdex/subdex-genesis-state

  generic-genesis-state:
    image: subdarkdex/generic-collator:v0.2.0
    volumes:
      - generic-genesis-state:/generic
    command: >
      /usr/local/bin/parachain-collator
      export-genesis-state --parachain-id=100
      /generic/generic-genesis-state
    
  dex-collator:
    labels: 
      - traefik.enable=true
      - traefik.http.routers.dex.rule=Host(`subdex.link`) && Path (`/dex`)
      - traefik.http.routers.dex.tls=true
      - traefik.http.routers.dex.tls.certresolver=letsEncrypt
      - traefik.http.routers.dex.service=dex
      - traefik.http.services.dex.loadbalancer.server.port=9944

    image: subdarkdex/subdex-collator:v0.2.0
    ports:
      - '40440:30333'
      - '9944:9944'
      - '6633:9933'
    volumes:
      - ./chainspec:/chainspec
      - dex-collator:/data
    depends_on:
      - validator-alice
      - validator-bob
      - validator-charlie
    command: >
      /usr/local/bin/start_dex_collator.sh
    networks:
      dex_net:
        ipv4_address: 172.28.1.8
        aliases:
          - dex-collator

  generic-collator:
    labels: 
      - traefik.enable=true
      - traefik.http.routers.generic.rule=Host(`subdex.link`) && Path(`/generic`)
      - traefik.http.routers.generic.tls=true
      - traefik.http.routers.generic.tls.certresolver=letsEncrypt
      - traefik.http.routers.generic.service=generic
      - traefik.http.services.generic.loadbalancer.server.port=9944
    image: subdarkdex/generic-collator:v0.2.0
    ports:
      - '40444:30333'
      - '7744:9944'
      - '7733:9933'
    volumes:
      - ./chainspec:/chainspec
      - generic-collator:/data
    depends_on:
      - validator-alice
      - validator-bob
      - validator-charlie
    command: >
      /usr/local/bin/start_generic_collator.sh
    networks:
      dex_net:
        ipv4_address: 172.28.1.10
        aliases:
          - generic-collator

  dex-runtime:
    image: subdarkdex/subdex-runtime:v0.2.0
    volumes:
       - subdex-chain-wasm-runtime:/runtime

  generic-runtime:
    image: subdarkdex/generic-runtime:v0.2.0
    volumes:
      - generic-chain-wasm-runtime:/runtime
    
  registrar:
    image: subdarkdex/subdex-registrar:v0.2.0
    volumes:
      - subdex-genesis-state:/subdex-genesis-state
      - generic-genesis-state:/generic-genesis-state
      - subdex-chain-wasm-runtime:/subdex-chain-wasm-runtime
      - generic-chain-wasm-runtime:/generic-chain-wasm-runtime
    depends_on:
      - validator-alice
      - validator-bob
      - dex-runtime
      - generic-runtime
      - dex-genesis-state
      - generic-genesis-state
    networks:
      dex_net:

volumes:
  subdex-genesis-state:
  subdex-chain-wasm-runtime:
  generic-genesis-state:
  generic-chain-wasm-runtime:
  dex-collator:
  generic-collator:
  validator_alice:
  validator_bob:
  validator_charlie:

networks:
  dex_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  
