version: '3'
services:
  validator-alice:
    image: parity/polkadot:master
    ports:
      - '30333:30333'
      - '6644:6644'
      - '9933:9933'
    volumes:
      - ./chainspec:/chainspec
      - validator_alice:/data
    command:
      - --chain=/chainspec/rococo_local.json
      - --port=30333
      - --ws-port=6644
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --alice
      - --no-prometheus
      - --no-telemetry

  validator-bob:
    image: parity/polkadot:master
    ports:
      - '30335:30335'
      - '9922:9922'
      - '9911:9911'
    volumes:
      - ./chainspec:/chainspec
      - validator_bob:/data
    command:
      - --chain=/chainspec/rococo_local.json
      - --port=30335
      - --ws-port=9922
      - --rpc-port=9911
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
      - --no-prometheus
      - --no-telemetry

  validator-charlie:
    image: parity/polkadot:master
    ports:
      - '30336:30336'
      - '8822:8822'
      - '8811:8811'
    volumes:
      - ./chainspec:/chainspec
      - validator_charlie:/data
    command:
      - --chain=/chainspec/rococo_local.json
      - --port=30336
      - --ws-port=8822
      - --rpc-port=8811
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --charlie
      - --no-prometheus
      - --no-telemetry

volumes: 
  validator_alice:
  validator_bob:
  validator_charlie:

